MODEL_IDS=[
"qwen25-3b-general","qwen3-4b-reasoning","qwen25-coder-3b","qwen25-vl-3b-chart",
"phi4-mini-deep","finbert-sentiment","finbert-tone","financial-news-distilroberta",
"financialbert-sentiment","chronos-small","timesfm-200m","moirai-small","granite-ttm",
"granite-tspulse","bge-reranker-base","minilm-embedding","whisper-small","kokoro-tts",
"sdxl-base","wan21-1.3b"]
MODEL_ADAPTERS={
"qwen25-3b-general":"llamacpp","qwen3-4b-reasoning":"llamacpp","qwen25-coder-3b":"llamacpp",
"qwen25-vl-3b-chart":"llamacpp_vision","phi4-mini-deep":"transformers_text_generation",
"finbert-sentiment":"transformers_text_classification","finbert-tone":"transformers_text_classification",
"financial-news-distilroberta":"transformers_text_classification","financialbert-sentiment":"transformers_text_classification",
"chronos-small":"chronos","timesfm-200m":"timesfm","moirai-small":"moirai","granite-ttm":"granite_ttm",
"granite-tspulse":"granite_tspulse","bge-reranker-base":"transformers_reranker",
"minilm-embedding":"sentence_transformers","whisper-small":"whisper","kokoro-tts":"kokoro",
"sdxl-base":"diffusers_sdxl","wan21-1.3b":"diffusers_wan"}
CAPABILITY_MODELS={
"chat":["qwen25-3b-general","qwen3-4b-reasoning"],"deep_reasoning":["qwen3-4b-reasoning","phi4-mini-deep"],
"coding":["qwen25-coder-3b","qwen3-4b-reasoning"],"vision":["qwen25-vl-3b-chart"],
"chart_analysis":["qwen25-vl-3b-chart","qwen3-4b-reasoning"],
"financial_sentiment":["finbert-sentiment","finbert-tone","financial-news-distilroberta","financialbert-sentiment"],
"forecasting":["chronos-small","timesfm-200m","moirai-small","granite-ttm"],
"anomaly_detection":["granite-tspulse"],"rerank":["bge-reranker-base"],"embedding":["minilm-embedding"],
"speech_to_text":["whisper-small"],"text_to_speech":["kokoro-tts"],"image_generate":["sdxl-base"],
"image_edit":["sdxl-base"],"video_generate":["wan21-1.3b"]}
