"use client";import{useEffect,useState}from"react";
type M={id:string;name:string;enabled:boolean;sourceRepo?:string;file?:string;warehousePath?:string;notes?:string;capabilities:string[];runtimeOrder:string[]};
export default function ModelCMS(){const[items,setItems]=useState<M[]>([]),[editing,setEditing]=useState<M|null>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
async function load(){setLoading(true);try{const d=await(await fetch("/api/powerx/cms/models",{cache:"no-store"})).json();setItems(d.items||[])}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function save(m:M){setMsg("Saving…");const r=await fetch("/api/powerx/cms/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...m,displayName:m.name})});setMsg(r.ok?"Saved":"Save failed");if(r.ok){setEditing(null);await load()}}
async function toggle(m:M){await save({...m,enabled:!m.enabled})}
function move(m:M,rt:string){const next=[rt,...m.runtimeOrder.filter(x=>x!==rt)];setEditing({...m,runtimeOrder:next})}
if(loading&&!items.length)return <div className="cmsGrid">{Array.from({length:6}).map((_,i)=><div className="cmsSkeleton" key={i}/>)}</div>;
return <><div className="cmsSummary"><div><strong>{items.filter(x=>x.enabled).length}</strong><span>Enabled</span></div><div><strong>{items.length}</strong><span>Total models</span></div><div><strong>On-demand</strong><span>Load policy</span></div></div><div className="cmsGrid">{items.map(m=><article className="cmsCard" key={m.id}><div className="cmsHead"><div><h3>{m.name}</h3><small>{m.id}</small></div><button className={"switch "+(m.enabled?"on":"")} onClick={()=>toggle(m)}><i/></button></div><div className="cmsChips">{m.capabilities.map(c=><span key={c}>{c}</span>)}</div><div className="cmsRoute"><span>Priority</span><b>{m.runtimeOrder.join(" → ")}</b></div><div className="cmsFoot"><span className={m.enabled?"good":"muted"}>{m.enabled?"Enabled":"Disabled"}</span><button className="cmsEdit" onClick={()=>setEditing({...m})}>Edit</button></div></article>)}</div>{editing&&<div className="editShade" onClick={()=>setEditing(null)}><div className="editPanel" onClick={e=>e.stopPropagation()}><div className="editTitle"><div><h2>Edit model</h2><p>{editing.id}</p></div><button onClick={()=>setEditing(null)}>×</button></div><label>Name<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Source repo / URL<input value={editing.sourceRepo||""} onChange={e=>setEditing({...editing,sourceRepo:e.target.value})}/></label><label>Model file<input value={editing.file||""} onChange={e=>setEditing({...editing,file:e.target.value})}/></label><label>Warehouse path<input value={editing.warehousePath||""} onChange={e=>setEditing({...editing,warehousePath:e.target.value})}/></label><label>Notes<textarea value={editing.notes||""} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><div className="priorityEditor"><span>Runtime priority</span><div>{["mobile","cpu","gpu16"].map(rt=><button key={rt} className={editing.runtimeOrder[0]===rt?"selected":""} onClick={()=>move(editing,rt)}>{rt}</button>)}</div><small>{editing.runtimeOrder.join(" → ")}</small></div><div className="editActions"><button onClick={()=>setEditing(null)}>Cancel</button><button className="saveBtn" onClick={()=>save(editing)}>Save changes</button></div><div className="saveMsg">{msg}</div></div></div>}</>}
